shabados/presenter

.gitignore
Dockerfile
README.md
docker-compose.yml

Added a `Dockerfile` and docker-compose file for easy installation and setup; useful for reproducible installation and usage in both dev and production.
Automatically fetches database from `shabadOS/database` release, and installs any app dependencies.

Dockerise application

---

styles/main.scss
templates/settings.html

This theme is like Night Light / Flux for dark environments. The yellow/red colors should not cause light adaptation.
Color of codefont is more in line with theme colors
Increase visibility of end of presentation graphic.

Add theme for low-light conditions

---

main.go
templates/head.html

- Remove bottom row of hotkeys from navigation page
- Add common presenter remote hotkeys
- Up, Down, Clear Display, Autoselect

Presenter clicker hotkeys

---

.gitignore
main.go
styles/main.scss
templates/banis.html
templates/display.html
templates/head.html
templates/index.html

- Update search queries
- Update banis
- Fix and Upgrade a few search related items

Update to new db

---

app/lib/consts.js
app/lib/db.js
app/package-lock.json
app/package.json
app/server.js

Automatic Database Updates

---

app/frontend/package-lock.json
app/frontend/package.json
app/frontend/src/index.js
app/frontend/src/lib/consts.js
app/lib/analytics.js
app/lib/consts.js
app/package-lock.json
app/package.json
app/server.js

Implements Sentry error reporting in production.
Closes #31.

Add Sentry support

---

.circleci/config.yml
app/electron/electron-wrapper.js
app/electron/entry.js
app/frontend/package.json
app/frontend/src/lib/consts.js
app/lib/consts.js
app/package.json
app/server.js
package.json

Small bug fixes to work better with Electron:
- Enable HTML5 routing with catch-all route in server
- Change port to 1699
- Bump version to 2.0.0-alpha
- Add release scripts

Electron fixes

---

.circleci/config.yml
app/electron/electron-wrapper.js
app/electron/entry.js
app/frontend/package.json
app/frontend/src/App.js
app/frontend/src/Presenter/StatusToast.css
app/frontend/src/Presenter/StatusToast.js
app/frontend/src/Presenter/index.js
app/frontend/src/lib/consts.js
app/lib/SessionManager.js
app/lib/Updater.js
app/lib/consts.js
app/lib/db.js
app/lib/settings.js
app/package-lock.json
app/package.json
app/server.js
app/settings.default.json

Well, well, well... Let's hope this works...
- Logging to file when in Electron environment
- Electron auto-updates
- Electron beta-updates
- Toast notifications with status from server
- Working CI config

Electron releases

---

.circleci/config.yml
app/lib/api.js
app/lib/consts.js
app/package.json
app/server.js
package.json

Paths were resolved relatively, and when packaged with electron, causes resolutions to be relative to the executable, usually a directory above. This broke any screens/calls that required reading from the filesystem.
This PR also changes some CI semantics to speed up builds and remove portable Windows builds.

Fix incorrect paths

---

app/frontend/src/Controller/Search.css
app/frontend/src/Controller/index.css
app/frontend/src/Presenter/Line.css
app/frontend/src/themes/Blue on White.css
app/frontend/src/themes/Darbar Sahib.css
app/frontend/src/themes/Day.css
app/frontend/src/themes/Night.css
app/frontend/src/themes/Philosophiae.css
app/frontend/src/themes/Yellow on Blue.css

To be pulled after multiple-lines branch

CSS Changes

---

README.md
app/frontend/package-lock.json
app/frontend/package.json
app/frontend/src/App.js
app/frontend/src/Controller/History.js
app/frontend/src/Controller/Menu.js
app/frontend/src/Controller/Navigator.js
app/frontend/src/Controller/Search.js
app/frontend/src/Controller/ToolbarButton.js
app/frontend/src/Controller/index.js
app/frontend/src/Presenter/Display.css
app/frontend/src/Presenter/Line.css
app/frontend/src/Presenter/index.css
app/frontend/src/Presenter/index.js
app/frontend/src/Settings/About.js
app/frontend/src/Settings/Hotkeys.js
app/frontend/src/Settings/SettingComponents.js
app/frontend/src/Settings/Sources.js
app/frontend/src/Settings/index.css
app/frontend/src/Settings/index.js
app/frontend/src/shared/Loader.css
app/frontend/src/shared/Loader.js
app/frontend/src/shared/withNavigationHotKeys.js

- Loads components lazily with chunk-splitting
- Uses direct imports to reduce bundle size
- Remove @material-ui/icons

Performance Enhancements

---

app/frontend/src/Controller/Bookmarks.css
app/frontend/src/Controller/Bookmarks.js
app/frontend/src/Controller/Menu.js
app/frontend/src/Controller/index.js
app/frontend/src/Presenter/index.js
app/frontend/src/lib/consts.js

- make the list icon for navigator into a play button to indicate playing a presentation
- make banis/bookmarks a star, matching internet convention for favoriting/saving/liking
- rename banis to bookmarks
close #152

feat(frontend): use clearer icons for navigator and banis

---

app/frontend/src/Controller/index.js

Restores the lastest URL upon re-opening controller
Closes #172

feat(frontend/controller): persist latest controller URL

---

app/frontend/src/Presenter/index.js
app/frontend/src/Settings/index.js
app/frontend/src/lib/controller.js
app/frontend/src/shared/ErrorFallback.css
app/frontend/src/shared/ErrorFallback.js

feat(frontend/presenter, frontend/settings): add Fallback UI in case of error

---

app/frontend/src/index.js
app/frontend/src/lib/analytics.js
app/frontend/src/lib/controller.js
app/frontend/src/lib/options.js
app/package.json
app/server.js
app/settings.default.json

Fixes Sentry error reporting/analytics and catches all unhandled process exceptions silently.

Release 2.0.0-beta.3

---

app/frontend/src/Controller/index.css
app/frontend/src/Presenter/index.css

More closely matches with v1 (v1 day theme comparing v2 avani theme)

Controller fixes

---

.circleci/config.yml
app/electron/entry.js
app/electron/updates.js
app/lib/consts.js
app/package-lock.json
app/package.json
package-lock.json
package.json

Release 2.0.0 🎉

---

.circleci/config.yml
app/electron/updates.js
app/frontend/src/Settings/About.js
app/frontend/src/Settings/index.css
app/frontend/src/Settings/index.js
app/frontend/src/lib/controller.js
app/frontend/src/lib/options.js
app/lib/SessionManager.js
app/lib/api.js
app/lib/settings.js
app/lib/utils.js
app/package-lock.json
app/package.json

- IP address with port of server in `About` page
- Enhanced mobile settings experience
- `private` setting is now off by default
- Settings are synchronised correctly across the network
- Duplicate settings entry of current machine is no more
- Updater now checks for updates AFTER reading beta setting
- Beta releases are properly set to GH pre-release by CI

Release 2.0.1

---

app/electron/updates.js
app/package.json

Release 2.0.2

---

app/frontend/src/Controller/index.css
app/package-lock.json
app/package.json
app/scripts/replay-log.js

Performance and bug fixes:
- Opening banis performance speed improvements
- Critical crash bug fixes from 2.0.3-beta
- Mobile touch friendliness from 2.0.3-beta

Release 2.0.3

---

app/electron/electron-wrapper.js
app/frontend/package-lock.json
app/frontend/package.json
app/frontend/src/Controller/Navigator.js
app/frontend/src/lib/consts.js
app/frontend/src/lib/controller.js
app/frontend/src/lib/utils.js
app/frontend/src/shared/NavigatorHotkeys.js
app/lib/SessionManager.js
app/lib/Sockets.js
app/lib/utils.js
app/package-lock.json
app/package.json
app/scripts/replay-log.js
app/server.js
app/settings.default.json

- Add support for Bani hotkeys (generated by searching for line endings etc)
- Asa Ki Vaar jump back to chakka support
- Auto-select for banis (jumps to the next jump line in a bani, otherwise AKV behaviour)
Needs some performance testing for sure though, since we do not have `line_types` in the DB, we are inferring information via regexes

Release 2.1.0-beta.1

---

app/electron/electron-wrapper.js
app/electron/entry.js
app/frontend/src/Overlay/Line.js
app/package.json

Fixes crash on startup introduced by beta.1 👀

Release 2.1.0-beta.2

---

.circleci/config.yml
app/frontend/public/index.html
app/frontend/src/Controller/History.css
app/frontend/src/Controller/History.js
app/frontend/src/Controller/Navigator.js
app/frontend/src/Controller/Search.css
app/frontend/src/Controller/Search.js
app/frontend/src/Controller/index.css
app/package.json

- Add clear cross button to search UI
- Add read timestamp to history and navigator
- Prevent Google translate suggestions
- Add empty CSS class to overlay
- Remove OS toast notifications
- Bani auto-jump and hotkeys
- Asa Di Vaar autoselect

Release 2.1.0

---

app/frontend/src/App.js
app/frontend/src/Controller/History.js
app/frontend/src/lib/utils.js
app/lib/History.js
app/lib/SessionManager.js
app/package.json

- History performance improvements. Should fix long usage crashes (needs further testing)
- Asa Di Vaar enhancements with auto-select limited to within Pauri and Chant

Release 2.1.1-beta.2

---

.circleci/config.yml
app/frontend/src/Overlay/index.js
app/package.json

Fixes bug with no translations in overlay

Release 2.2.1

---

.circleci/config.yml
app/electron/window.js
app/package.json
get-changelog.sh

Really just wanted to test preliminary release notes (under releases), correct non-prerelease releases
- Hide electron menu from prod

Release 2.2.2

---

app/lib/logger.js
app/lib/utils.js
app/package.json

Urgent bug fix for crash on open (log folder does not exist)

Release 2.3.1

---

app/electron/window.js
app/frontend/src/Presenter/index.js
app/frontend/src/lib/electron-utils.js

Note: Enables nodeIntegration
Fixes #272

fix(frontend/presenter, electron): use Electron mechanism to fullscreen window

---

app/frontend/src/Settings/index.css

fixes color of title in hotkeys and translation sources
close #279

fix(frontend/settings): color text correctly

---

app/frontend/src/App.js
app/frontend/src/Controller/Navigator.js
app/frontend/src/Controller/index.js
app/frontend/src/Overlay/index.js
app/frontend/src/Presenter/Display.js
app/frontend/src/Presenter/index.js
app/frontend/src/Settings/CopyButton.js
app/frontend/src/Settings/DynamicOptions.js
app/frontend/src/Settings/Hotkeys.css
app/frontend/src/Settings/Hotkeys.js
app/frontend/src/Settings/SettingComponents.js
app/frontend/src/Settings/Sources.css
app/frontend/src/Settings/Sources.js
app/frontend/src/Settings/index.js
app/frontend/src/lib/consts.js
app/frontend/src/lib/contexts.js
app/frontend/src/lib/controller.js
app/frontend/src/lib/hooks.js
app/frontend/src/lib/keyMap.js
app/frontend/src/lib/options.js
app/frontend/src/shared/CopyHotkeys.js
app/frontend/src/shared/ErrorFallback.js
app/frontend/src/shared/NavigatorHotkeys.js
app/lib/SessionManager.js
app/lib/Sockets.js
app/lib/api.js
app/lib/db.js
app/lib/utils.js

Copy hotkeys

---

app/frontend/src/Settings/Hotkeys.css
app/frontend/src/Settings/Hotkeys.js
app/frontend/src/lib/hooks.js
app/frontend/src/lib/keyMap.js
app/frontend/src/shared/CopyHotkeys.js
app/package-lock.json
app/package.json

- Add common bookmarks
- Minor hotkey amendments

Release 2.5.0

---

app/frontend/src/Controller/History.css
app/frontend/src/Controller/Navigator.css
app/frontend/src/Controller/Navigator.js
app/frontend/src/Controller/index.css

this avoids hiding content with ellipsis and makes the activities display lines uniformly
close #323

feat(frontend/controller): wrap lines and separate with line border

---

README.md

This will fix the issues where badges are not showing up properly and hyperlinks are broken.

Update and rename README.adoc to README.md

---

app/frontend/src/Settings/index.css
app/frontend/src/lib/options.js

Closes #363  
Closes #368 
Closes #433

Settings Layout Improvements

---

app/frontend/src/Controller/Navigator.css
app/frontend/src/Controller/Navigator.js
app/frontend/src/Controller/ShabadInfo.css
app/frontend/src/Controller/ShabadInfo.js
app/lib/db.js

Adds info button in frontend/controller navigation bar
Closes #378

feature: info button

---

app/frontend/src/Controller/ShabadInfo.js

fix: improve Shabad info popup formatting

---

app/electron/electron-wrapper.js
app/electron/updates.js

fix(electron): supress electron updater network errors

---

app/electron/splashscreen/index.css

feat(electron): add radial background

---

app/frontend/src/Controller/Navigator.js

fix: crash on up/down GUI buttons on first/last lines

---

app/frontend/src/Controller/Search.js

fix(frontend/controller): add full-stop after author

---

app/frontend/src/Controller/Search.css

fix(frontend/controller): truncate translations after 2 lines

---

app/frontend/src/shared/NavigatorHotkeys.js

excludes the classNames which are not 'desktop app' or 'presenter'
fixes #401

fix(frontend/presenter): clicking on plus should not toggle next line

---

app/frontend/src/Controller/Search.js

Change the citation format to hyphenated (BOS style)
**Before:** 
**After:**
5 minutes -> 30 seconds for fix and remaining for opening issue and PR
Fix #575 
@bhajneet @Harjot1Singh

fix(frontend/controller): change default citation format

---

app/frontend/src/Controller/Search.js
app/frontend/src/shared/ThemeLoader.js

Fixes ESLint errors that are causing [build to fail](https://app.circleci.com/pipelines/github/ShabadOS/desktop/361/workflows/79365564-2e68-4005-aadd-56c509ae8e3a/jobs/2066/parallel-runs/0/steps/0-103). 
`npm run lint:frontend` no errors are thrown only warnings
<details>
<summary> See Log </summary>
<pre>
> @shabados/desktop@0.0.1 lint /Users/saihaj/Desktop/shabad-os/desktop
>
> @shabados/desktop@0.0.1 lint:frontend /Users/saihaj/Desktop/shabad-os/desktop
> cd app/frontend && npm run lint
>
>
> @shabados/frontend@0.1.0 lint /Users/saihaj/Desktop/shabad-os/desktop/app/frontend
> eslint .
/Users/saihaj/Desktop/shabad-os/desktop/app/frontend/src/Controller/Navigator.js
39:1  warning  @param "id" does not match an existing function parameter  jsdoc/check-param-names
39:1  warning  Missing …

style(frontend): shorten max line length of destructured properties in Search

---

app/frontend/src/Settings/OverlaySettings.js

Adds a button in overlay settings to link to theme tool and also changes the description.
**Before**
**After**
30 minutes
Fix #506 
@Harjot1Singh

feat(frontend/settings): theme tool

---

app/frontend/package-lock.json
app/frontend/package.json
app/frontend/src/Controller/History.js
app/frontend/src/Controller/Navigator.js
app/frontend/src/Controller/Search.js
app/frontend/src/Controller/ShabadInfo.js
app/frontend/src/lib/consts.js
app/frontend/src/lib/utils.js
app/frontend/src/shared/CopyHotkeys.js
app/lib/db.js
app/package-lock.json
app/package.json

Updates to `gurmukhi-utils@3.1.0`. This allows for removing some existing code and refactoring to use more of `gurmukhi-utils`.
Inserting and deleting accents are resolved, as the input is no longer converted to ascii (but let me know if this behaviour is incorrect).
Also does not incorrectly highlight full word matches with any trailing spaces.
Finally, first-letter searching with accented characters like `Z` will correctly return results.
- Unicode inputs
- Ascii inputs
- Deleting and typing in both
- Searching for test queries with first letter accents
1.5hrs
Fixes #166 
Fixes #344 
Fixes #540
@bhajneet

feat: unify accent insertion and match accented first letter input

---

app/frontend/src/Settings/About.js
app/server.js

Create an action in backend so that frontend can trigger the action. 
**Now**
30 minutes
Fix #478 
@Harjot1Singh @bhajneet

feat(frontend/settings): add "open logs folder" button

---

package-lock.json
package.json

Update electron to v7.3.2 to fix security issues. https://github.com/saihaj/ShabadOSdesktop/network/alert/app/package-lock.json/electron/open
Release notes for electron v7.3.2 -> https://www.electronjs.org/releases/stable?version=7#release-notes-for-v732
@Harjot1Singh

build(electron): update electron to fix CVE issues

---

app/frontend/src/Settings/OverlaySettings.css

Increases margin top and bottom
**Before**
**After**
5 mins
Fix #519 
@bhajneet @Harjot1Singh

fix: vertical paddings of buttons in settings

---

app/electron/electron-wrapper.js
app/frontend/src/Controller/Navigator.js
app/frontend/src/Presenter/Line.js
app/frontend/src/Presenter/index.js
app/frontend/src/Settings/DynamicOptions.js
app/frontend/src/Settings/OverlaySettings.js
app/frontend/src/Settings/Sources.js
app/frontend/src/Settings/index.js
app/frontend/src/lib/controller.js
app/frontend/src/lib/options.js
app/frontend/src/lib/utils.js
app/frontend/src/shared/NavigatorHotkeys.js
app/lib/utils.js
app/scripts/replay-log.js
app/server.js

The double blank line in `electron-wrapper.js` prevents linting from passing. 
*This ends this.*
10 hours
Fix Fix Fix
@saihaj

style: remove double blank lines

---

app/frontend/src/Controller/ShabadInfo.js

30 seconds
Fixes #600
@Harjot1Singh

fix(frontend/controller): update links to database viewer

---

CONTRIBUTING.adoc
README.adoc
app/frontend/package.json
app/package.json
package-lock.json
package.json

Rename desktop to presenter
5 mins
@Harjot1Singh 
@Harjot1Singh need to fix circle ci

docs: update readme to rename desktop to presenter

---

app/frontend/src/Controller/ShabadInfo.css
app/frontend/src/Controller/ShabadInfo.js

Cleaned up some code in the ShabadInfo component
@saihaj

refactor(frontend/controller): correctly name CSS classes and remove inline handlers

---

app/frontend/src/Controller/History.js
app/frontend/src/Settings/OverlaySettings.js
app/frontend/src/shared/ErrorFallback.js

Fixes Lint issues on dev
1 min
Dev CI Failing
@Harjot1Singh

style(frontend): fix inconsistent indentation

---

app/package-lock.json
app/package.json

build: bump to 2.8.0
Fix #
@saihaj @bhajneet

build: bump to 2.8.0

---

app/package-lock.json
app/package.json

build(app): bump to v2.9.0

---

app/frontend/src/Presenter/Line.css
app/frontend/src/Presenter/Line.js
app/frontend/src/lib/options.js

- Syllabic weights (@bhajneet)

Release 2.9.0

---

app/package-lock.json
app/package.json

build(app): bump to v2.10.0

---

app/package-lock.json
app/package.json

build(app): bump to v2.10.0 (#633)

---

app/package-lock.json
app/package.json
package.json

Release 2.10.1

---

CONTRIBUTING.md
README.md
app/frontend/src/Settings/OverlaySettings.js

Update to use new docs site
- 2 mins

feat: update links to docs

---

app/package-lock.json
app/package.json

build(app): bump to v2.11.0

---

app/package-lock.json
app/package.json
package-lock.json
package.json

build: update electron

---

app/frontend/src/Settings/OverlaySettings.js

fix: update tutorial link

---

app/package-lock.json
app/package.json

Code-signing is back! This is a placeholder release to push this out of the door

build(app): bump to v2.11.1

---

app/electron/electron-wrapper.js
app/electron/menu.js
app/package.json

Attempt to fix global copy paste on macOS.
5mins fix and couple hours of research

feat: add menu on macos

---

app/package.json

build: bump patch version

---

app/electron/electron-wrapper.js
app/electron/menu.js
app/package.json

build(app): bump to v2.11.2

---

app/frontend/src/ScreenReader/index.css
app/frontend/src/ScreenReader/index.js

Existing (left) vs. This PR (right)
-

feat: add screenreader with paragraph blocks

---

CONTRIBUTING.md
README.md

In an effort to streamline our github for developers: 
- point to new shared docs area on our website
- update readme with relevant info for different types of readers (consumers, contributors, etc.)
And update any mentions of GPL to MIT in the readme (which should have been done earlier)
15 mins

docs: update readme and contributing with new info
