shabados/presenter

styles/main.scss, templates/settings.html
This option only worked in Chrome and was the same as normal in Electron
=> Remove space-evenly option for layout

main.go
This allows search results to show up except for the affected lines
(Affected being those that have incorrect "first letters" generated)
This does not resolve the bug entirely, simply allows other search results to show up.
=> Add check to remove search crashes

app/lib/db.js
Sort lines by Bani Line's line group and Line's order id.
Notes:
* line_id seems to be a non-integer reference. Used to be integer in @shabados/database@3.0.0.
* Forces join eager algorithm.
* Why the query used to work? Builder on eager makes the orderBy only work on the left join query. @shabados/database@3.0.0 used to do the Bani_Lines/Lines via innerjoin. I think that's why the older query worked. Also, that query was only doing Bani Lines. This query also gets Bani document along with Lines documents.
=> Fix bani lines query

app/frontend/src/Controller/Search.css, app/frontend/src/Controller/Search.js, app/frontend/src/lib/consts.js, app/frontend/src/lib/controller.js, app/lib/db.js, app/package-lock.json, app/package.json, app/server.js
Adds support for anchor based searching.
Closes #147.
=> Add Full Word search

app/frontend/src/Presenter/Line.css, app/frontend/src/lib/consts.js
the previous implementation was in hard vh units, since switching to a master font-slider, we need to use flexible units of measure in the line
this also fixes word-spacing issues and allows for more fine-tuned font-size changes
Related #75 #191
=> fix(frontend/presenter): allow flexible font-sizing

app/electron/electron-wrapper.js, app/frontend/src/Presenter/Line.css, app/frontend/src/Settings/SettingComponents.css, app/frontend/src/Settings/Sources.css, app/frontend/src/shared/Loader.css, app/frontend/src/themes/Avani.css, app/frontend/src/themes/Blue on White.css, app/frontend/src/themes/Darbar Sahib.css, app/frontend/src/themes/Day.css, app/frontend/src/themes/Night.css, app/frontend/src/themes/Philosophiae.css, app/frontend/src/themes/Yellow on Blue.css
This should change the color of the loader, the pop up selectors, as well as hover items in said pop up selector. In addition Avani theme was updated to move away from purple and more towards red while also shifting to blue and yellow-red accents.
Image of new Avani:
Image of new Night:
Also fixed sources in Avani (#233):
=> feat(frontend): add theme colors to material ui

.circleci/config.yml, hooks/sign-windows.js, package.json
CircleCI's Windows user account does not give access to importing certificates into the `Current User` store. Thus, they must be imported to `Local Machine` (which ironically, requires elevated priviledges, but still works).
=> build(ci): custom code-signing Windows script

.circleci/config.yml, app/electron/entry.js, app/electron/esm-wrapper.js, app/frontend/src/lib/controller.js, app/lib/analytics.js, app/lib/error.js, app/package.json, app/server.js
- More reliable error handling
- Restart backend on crash
- Smaller reconnection timeout for frontend WebSockets
- Fix Sentry not initialising correctly in backend due to silent error
- *Catch unhhandled rejections and log them* <-- This is most likely why we haven't got logs for a bunch of bugs we can somewhat reproduce
=> Release 2.0.3-beta.1

app/package-lock.json, app/package.json
- Fix timestamp formatting in navigator and history, fixes #341
- Do not log to stdout in production, fixes #331 (long usage crash)
- Performance improvements with memoisation and refactoring to contexts + hooks
- History performance improvements
- Ensure Sentry crash logs are flushed before restarting backend
- Asa Di Vaar auto-select enhancements (auto-select limited to within Pauri or Chant)
=> Release 2.2.0

app/frontend/src/Presenter/Line.css
this is not required for most modern browsers on desktop. this may have also affected safari on macOS. without this, it would try to fit all the lines into the space for next-lines/previous-lines. can be visualized by reverting this commit and specifying hidden overflow for next line.
close #420
=> fix(frontend/presenter): add explicit height for ios webkit

app/frontend/src/shared/CopyHotkeys.js
this commit e24508f is the one. Sorry for this mess.
closes #436
=> feat: remove vishraam symbols from copy hotkeys

app/frontend/src/Controller/Search.js, app/package-lock.json
Closes https://github.com/ShabadOS/desktop/issues/170. Does not change the functionality of the `firstLetter` search highlighting, but modifies the `fullWord` highlighting to include all words.
I tried the following test cases:
1. The word is at the beginning of the line.
2. The word comes after a special character.
3. Trailing space after the word.
4. Ensured the first letter search still worked.
Happy to write unit tests once those exist (if they exist).
I didn't have permission to push to ShabadOS/desktop, and the instructions said to fork so that's what I did - not as well versed with the workflow so let me know if I need to change things.
I was surprised at some of the eslint rules, especially the extraneous semicolon being enforced.
@saihaj @Harjot1Singh
=> fix(frontend/controller): highlight full words in search

app/frontend/src/Controller/Navigator.css, app/frontend/src/Controller/Navigator.js
older smartphone's cannot fit all the icons available in the navigator activity
fix #491
---
Tested on iPhone 5 320x568 via inspect tool and Pixel 3a via physical device using Firefox
Took about 5 minutes. The PR took an additional 5 minutes. 😂
=> fix(frontend/controller): hide gui arrow buttons for mobile browsers

app/lib/SessionManager.js
fixes #351
Simple fix to compare IDs correctly. Before it was comparing an array with a string.
Tested with first and second lines of various shabads. Also tested with Asa Ki Vaar. Noticed that the `<<` symbol is not shown in AKV. Can't remember if that was how it was before, but regardless it still looks okay and functions the same. You always can see where the jump will take you.
I won't lie, this took a lot longer than I expected. Took 60 minutes to read the code base and hone in on the area. Another 30 minutes to figure out how to debug in VS Code. And then finally another 15 to resolve and test various shabads.
=> fix(backend): compare like types for nextLineId

app/frontend/src/App.js
Reloads settings when the sources have been retrieved from the backend. Fixes race conditions which end up resulting in the translations not rendering in both the overlay and presenter, since React is not aware that the change happened.
- Set network to "Fast 3G" in network inspector and reload. Translations do not work originally.
15 mins
Fixes #535 
@bhajneet
=> fix(frontend): reload settings when default options have been modified

app/frontend/src/Settings/Sources.js, app/frontend/src/Settings/index.js
Fixes the updating of source options. Due to a regression, no `setSettings` function was supplied to the `Sources` component, thus, it was unable to propagate any user changes.
✔ Change sources and observe changes on presenter 
2 minutes
Fixes #538
@bhajneet
=> fix(frontend/settings): update source settings when option is changed

app/frontend/src/Settings/About.js, app/lib/analytics.js, app/lib/api.js
Add release info to about page, this info can also be used in loggers so logs will reflect which os is running more effectively
- since adding a feature, I don't think there could be anything broken by something as simple as this
13 mins of reading docs, 1 minute of coding, 1 minute of PR = 15 mins
Fix #365
@Harjot1Singh
=> feat(frontend/settings): add os.release to about page and sentry logger

app/frontend/src/Settings/SettingComponents.js, app/frontend/src/Settings/index.js, app/frontend/src/lib/options.js
A new component that `onOpen` will fetch list of available themes from server.
Before: restart ShabadOS to load overlay themes 
After
~3 hours
Closes #448 
@Harjot1Singh 
Need to fix this and then should be good to go:
=> feat(frontend/settings): refresh overlay dropdown on focus

app/frontend/src/Controller/Navigator.js, app/frontend/src/lib/keyMap.js
the custom hotkeys for first / last in navigator were lower priority than the default navigation hotkeys used in other activities
Also updated the settings page:
- used different shabads as tests
- confirmed not breaking banis
- tried in other activities for whatever reason
About 3 hours. Spent about 30 minutes figuring out where the issue was coming from. Then another 2 hours trying to fix it. Then spent 5 minutes on copying the solution being used in `search.js` to `navigator.js` Remaining time was spent on thinking through hotkey names/descriptions for settings.
Fix #504 
@Harjot1Singh
=> fix(frontend/controller): use custom first and last hotkeys in navigator

app/frontend/src/shared/NavigatorHotkeys.js
fix(frontend/shared): add mouseTargetRef to dependency array of hook
Before: 
After:
15 minutes finding the issue, 1 minute for fix, 10 minutes trying to figure how to upload `.svg` here but ended up with screenshots. 
Fixes #564
@Harjot1Singh
=> fix failing dev builds

app/frontend/src/lib/hooks.js
Work around for sudodoki/copy-to-clipboard#90
* Works on very first hotkey stroke
* Also works when you change shabads 
4 hours
Fix #437 
@Harjot1Singh
=> fix(frontend): copy on first hotkey stroke

app/frontend/src/lib/hooks.js, app/frontend/src/shared/NavigatorHotkeys.js
Only advances the presenter slide if the window is focused. Uses an approach of taking a mouse click as a focus event on anything that is not Mac, and the focus event on Mac.
See #388 for more description and considered solutions.
- Mac
- Windows
- Electron vs Browser
- 1hr20
Closes #388 
@bhajneet
=> feat(frontend/presenter): only advance on click if focused

app/frontend/src/Settings/OverlaySettings.js, app/frontend/src/lib/consts.js
On dev the port for overlays should be same as frontend and that is `3000` and for production `1699`
**Before**
**After**
2 mins for fix and don't know for how long I have been complaining
@Harjot1Singh
=> fix: correct overlay port for dev

app/frontend/src/lib/options.js
Rename `Settings`>`System Options`>`All Displays` to `Launch on All Displays`
**Before**
**After**
5 minutes -> 30 seconds for fix and rest for git related
Fixes #366
@bhajneet @Harjot1Singh
=> fix(frontend/settings): add descriptive name for all displays toggle

app/frontend/src/shared/CopyHotkeys.js
Hide line number in copying depends on the value of toggle -> `Settings` > `Display` > `Hide Line Endings`
Toggled settings opting then testing copying and works as expected for translations and transliterations.
10 minutes
Fixes #587
@Harjot1Singh @bhajneet
=> fix(frontend): hide line numbers from copied lines depending on settings

.gitignore, .vscode/extensions.json
Add VSCode plugins in `.vscode/extensions.json`. Explanation of why `.gitignore` only excludes `.vscode/extensions.json` is [here](https://github.com/ShabadOS/desktop/issues/196#issuecomment-659457270).
10 minutes
Fix #196 
@Harjot1Singh @bhajneet 
Note: Push changes here if you would like to suggest more plugins
=> build: add vscode plugin recommendations

app/electron/electron-wrapper.js, app/electron/splashscreen/index.html
Add version number to splash screen
**Before**
**After**
40 minutes
Fixes #490
@Harjot1Singh @bhajneet
=> feat(electron): add version number to splash screen

app/frontend/src/shared/NavigatorHotkeys.js
When the navigator is closed, the down/right arrow does not navigate to the next line. This is because some checks were introduced in #451 to ensure no element has been clicked when using mouse navigator. It appears our check was too stringent, and did not account for a hotkey because the initiator of the transition.
- ✅ Down + Right arrows advance line
- ✅ Clicking the plus sign does not advance the line
- ✅ No boundary bugs when on last line
10 mins
Fix #¯\_(ツ)_/¯#
This might be something that has been raised by @Sarabveer.
@bhajneet @saihaj
=> fix(frontend/presenter): fix next line hotkey when navigator is closed

app/frontend/src/lib/electron-utils.js
Previously only was toggling into fullscreen but not out in web browser environments. Does not check or exit on the same keypress (ctrl-f).
- Toggles in and out of fullscreen in web browser environments
- 2 minutes
Fix #oopsie
@saihaj @bhajneet
=> fix: correctly toggle in and out of fullscreen on hotkey in browsers

app/frontend/src/shared/CopyHotkeys.js
Use the source abbreviation to have BoS style when copy pasting as done for serach results in #575
15 mins - 30 seconds for fix and rest time spent to find the line because I forgot where it was : )
Fix #620 
@Harjot1Singh
=> fix(frontend/presenter): use source abbreviation in copy citation hotkey

app/frontend/src/Presenter/Line.css, app/frontend/src/Presenter/Line.js, app/frontend/src/lib/options.js
Adds options to see syllabic weight of each word or the syllable count of the entire line for presented gurmukhi
Examples:
<image src="https://user-images.githubusercontent.com/14130567/98272660-54cce380-1f5f-11eb-971c-9e1fffbb073e.png" width="600">
<image src="https://user-images.githubusercontent.com/14130567/98272763-70d08500-1f5f-11eb-98df-6e4951abf07c.png" width="600">
<image src="https://user-images.githubusercontent.com/14130567/98272786-7928c000-1f5f-11eb-8772-ca33ae2103b9.png" width="600">
- various options juggling
- prev/next lines
- different bookmarks
90-120 mins
@Harjot1Singh
=> feat(frontend/presenter): add options for syllabic weights and counts of gurmukhi lines

package.json
Must use the same appId throughout the lifecycle of the same app, else updates and other things may break. Reverting back to original appId.
=> build: rename appId to original com.shabados.desktop

app/electron/electron-wrapper.js, app/electron/window.js, app/frontend/src/lib/electron-utils.js, app/package-lock.json, app/package.json
As per #667, the fullscreen hotkey was no longer working in Electron. This was investigated, and is actually a regression of #613, as the release notes specify that `require('electron').remote` is deprecated in favour of `require('@electron/remote')`.
This PR introduces the necessary `@electron/remote` package and adds the required initialisation commands to restore the original behaviour/functionality.
Fixes #667
=> fix: call electron remote module correctly

app/lib/zoom.js
Zoom.js imports were trying to access non-existent aliased imports. They've been changed to relative imports now.
Without this change, the app was unrunnable because the imports were not resolvable.
=> fix: correct zoom imports to be relative instead of non-existent aliased

app/electron/splashscreen/index.html
Due to an Electron update (in #652), the current method of fetching and displaying the version number (see #590) no longer works.
This PR rectifies this issue by using the new @electron/remote package in place of the deprecated `remote` method of the `electron` package.
Fixes issue described in #660.
=> Show version number in splash screen again

app/frontend/src/Settings/index.css
As described by #655, if the settings content was beyond 100% of the viewport height, the main element doesn't actually follow along and stretch to hold the full content.
This PR makes the settings background colour fill the screen regardless of the content length.
Flex-grow is used to make the main element always stretch to at least the size of the viewport. If the content is longer than the viewport size, it will keep stretching to fit all of the content. This means the background colour will always be visible.
=> Make settings background colour fill the screen regardless of content length

app/package-lock.json, app/package.json, package-lock.json
Implictly bumps sqlite3 package, which should allow for native electron binaries to be downloaded - this will remove any native build step in the pipeline with `gyp`, so pipelines should start working again (bar signing on windows!)
=> build: upgrade to latest @shabados/database package

apps/frontend/src/Controller/Navigator.js, apps/frontend/src/Controller/Search/index.js, apps/frontend/src/Controller/index.tsx, apps/frontend/src/Presenter/index.js, apps/frontend/src/Settings/index.js
React Router DOM package is changing things like `useHistory()` in v5 to `useNavigate()` in v6. See [here](https://reactrouter.com/en/main/upgrading/v5) for more details.
The app currently uses the old `useHistory()` hook from the React Router package, but the app has v6 installed, so we'd like to update usages of the old function wherever possible.
We also want to replace `<Redirect />` with `<Navigate />`.
This PR:
* Replaces `useHistory()` usages with `useNavigate()`, the new function for v6 of the router package.
* Replaces `<Redirect />` with `<Navigate />`.
Implements #678.
=> Upgrade to React Router v6 functions
